#!/bin/sh
. /etc/rc.common

StartService() {
  /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -z
  for i in $(/sbin/ifconfig -a | grep "en[0-9]" | cut -d':' -f1); do
    sudo /sbin/ifconfig $i ether $(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
  done
  networksetup -detectnewhardware
}

StopService() {
  return 0
}

RestartService() {
  return 0
}

RunService "$1"
