#!/bin/sh

/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -z
for i in $(/sbin/ifconfig -a | grep "en[0-9]" | cut -d':' -f1); do
  /usr/sbin/networksetup -setairportpower "$i" off
  /usr/sbin/networksetup -setairportpower "$i" on
  # http://osxdaily.com/2012/03/01/change-mac-address-os-x/#comment-348506
  mac="$(ruby -e 'puts ("%02x"%((rand 64)*4|2))+(0..4).inject(""){|s,x|s+":%02x"%(rand 256)}')"
  /sbin/ifconfig "$i" ether "$mac"
done
